### ISSUE TITLE
Failed to activate the linter-lsc package

### ISSUE THREAD

**Issue by marcoemrich** [AtomLinter/linter-lsc#11]
[Enter steps to reproduce below:]

1. open settings -> Install
2. Try to install linter-lsc

**Atom Version**: 1.0.11
**System**: Linux Mint
**Thrown From**: [linter-lsc](https://github.com/AtomLinter/linter-lsc) package, v2.2.1

### Stack Trace

Failed to activate the linter-lsc package

```
At undefined is not a function

TypeError: undefined is not a function
  at Function.install (/home/memrich/.atom/packages/linter-lsc/node_modules/atom-package-deps/lib/main.js:29:19)
  at Object.module.exports.activate (/home/memrich/.atom/packages/linter-lsc/lib/init.coffee:6:34)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:243:19)
  at /usr/share/atom/resources/app.asar/src/package.js:224:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:216:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:486:21)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:371:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
  5x -5:54.9.0 core:undo (atom-text-editor.editor.is-focused)
  2x -5:51.4.0 core:redo (atom-text-editor.editor.is-focused)
     -5:49.2.0 core:undo (atom-text-editor.editor.is-focused)
  2x -5:48.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:47.7.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -5:47.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -5:45.8.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -5:45.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:42.4.0 core:save (atom-text-editor.editor.is-focused)
  4x -5:41.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:40.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:40.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  6x -5:40.3.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -5:05.0 core:save (atom-text-editor.editor.is-focused)
     -2:32.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:37.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.7.2
autoclose-html, v0.19.0
autocomplete-html-entities, v0.1.0
editorconfig, v1.2.0
emmet, v2.3.12
esformatter, v1.12.0
file-type-icons, v0.7.3
foldername-tabs, v0.1.5
javascript-snippets, v1.0.0
language-javascript-better, v1.5.0
language-livescript-edge, v1.0.2
linter, v1.5.1
linter-jshint, v1.2.0
linter-lsc, v2.2.1
synced-sidebar, v0.4.0
tree-view-git-modified, v0.5.10
tree-view-git-status, v0.2.0

# Dev
No dev packages
```

**Comment by k2b6s9j** [comment]
@steelbrain Looks like `package-deps` had an issue.

**Comment by steelbrain** [comment]
@k2b6s9j upgrade it's version and it'll be work again.

**Comment by k2b6s9j** [comment]
@johngeorgewright Version upgrade?

**Comment by johngeorgewright** [comment]
On it.

**Comment by steelbrain** [comment]
@johngeorgewright Wait a sec, I'll release a version with more features and removed dependencies.

**Comment by steelbrain** [comment]
`v2.1.0` is out.

**Comment by johngeorgewright** [comment]
OK... hopefully that fixed things. I have a linux machine at home which I can test on.

Until then, @marcoemrich is it working for you?

**Comment by contil** [comment]
[Enter steps to reproduce below:]

1. Update all packages
2. Error appears on activating the package (after installation /upgrade finishes)

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-lsc](https://github.com/AtomLinter/linter-lsc) package, v2.2.3


### Stack Trace

Failed to activate the linter-lsc package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.install (/Users/contil/.atom/packages/linter-lsc/node_modules/atom-package-deps/lib/main.js:14:15)
    at Object.module.exports.activate (/Users/contil/.atom/packages/linter-lsc/lib/init.coffee:6:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:469:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:324:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:464:19)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
autocomplete-paths, v1.0.2
go-plus, v3.5.1
language-cfengine3, v0.1.0
language-imba, v0.1.0
language-puppet, v0.14.0
language-sake, v0.1.0
language-slim, v0.5.0
linter, v1.5.1
linter-ansible-lint, v0.0.7
linter-csslint, v1.0.5
linter-gcc, v0.3.8
linter-golinter, v1.0.0
linter-gotype, v0.1.0
linter-govet, v0.1.5
linter-haml, v1.0.0
linter-js-standard, v3.2.0
linter-js-yaml, v1.1.2
linter-jscs, v2.0.5
linter-lsc, v2.2.3
linter-php, v1.0.3
linter-puppet-lint, v0.5.0
linter-pylint, v1.0.0
linter-shellcheck, v1.0.1
linter-stylelint, v1.0.4
linter-tidy, v1.0.1
linter-tslint, v0.4.0
minimap, v4.13.3

# Dev
No dev packages
```

**Comment by johngeorgewright** [comment]
I think I'm going to roll this change back until I understand why people are having problems with the `atom-package-deps` package.

**Comment by marcoemrich** [comment]
I tried it. The issue persists :(

Is there anything I can try to help you?

**Comment by marcoemrich** [comment]
Ahh sorry -  2.2.4 work. It was just a strange atom caching problem.

**Comment by marcoemrich** [comment]
I even tried to remove atom-package-deps from the package.json, but commenting out the require was actually enought. thanks!

**Comment by steelbrain** [comment]
@johngeorgewright the version they have of `atom-package-deps` is master on the repo, I don't see nothing that has a `.install` in it on line 14 here https://github.com/steelbrain/package-deps/blob/master/lib/main.js#L14
It is either that the error's are not being resolved by source maps correctly or that even after the upgrade, the users were running an old version of it.
